- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        # NOTE(rpittau) temporary non-voting to be able to land fixing patches
        - ironicclient-functional:
            voting: false
        - ironicclient-tempest:
            voting: false
    # NOTE(rpittau) temporary disabling to be able to land fixing patches
    # gate:
      # queue: ironic
      # jobs:
        # - ironicclient-functional
        # - ironicclient-tempest
